name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: test & build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@master
      with:
        go-version: 1.16.5

    - name: Dependencies installation
      run: go mod download

    # здесь должны быть запуск тестов но в коде их нет
    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build

  docker-build:
    name: docker build
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: .
          push: false
